### ISSUE TITLE
error executing script

### ISSUE THREAD

**Issue by ToXinE** [danilovazb/GitMiner#3]
with the command : `$ python git_miner.py -q 'filename:wp-config extension:php FTP_HOST in:file' -m wordpress -o result.txt`
```
 ██████╗ ██╗████████╗███╗   ███╗██╗███╗   ██╗███████╗██████╗
██╔════╝ ██║╚══██╔══╝████╗ ████║██║████╗  ██║██╔════╝██╔══██╗
██║  ███╗██║   ██║   ██╔████╔██║██║██╔██╗ ██║█████╗  ██████╔╝
██║   ██║██║   ██║   ██║╚██╔╝██║██║██║╚██╗██║██╔══╝  ██╔══██╗
╚██████╔╝██║   ██║   ██║ ╚═╝ ██║██║██║ ╚████║███████╗██║  ██║
 ╚═════╝ ╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ v1.1
 Automatic search for GitHub.

 + Autor: Danilo Vaz a.k.a. UNK
 + Blog: http://unk-br.blogspot.com
 + Github: http://github.com/danilovazb
 + Gr33tz: l33t0s, RTFM

 +[WARNING]------------------------------------------+
 | DEVELOPERS ASSUME NO LIABILITY AND ARE NOT        |
 | RESPONSIBLE FOR ANY MISUSE OR DAMAGE CAUSED BY    |
 | THIS PROGRAM                                      |
 +---------------------------------------------------+


Traceback (most recent call last):
  File "git_miner.py", line 223, in <module>
    GitMiner().start()
  File "git_miner.py", line 216, in start
    HTML = self.accessWeb(url_acesso)
  File "git_miner.py", line 198, in accessWeb
    if " find any code matching" in acc.text:
AttributeError: 'Response' object has no attribute 'text'

```

Same with other commands

**Comment by herdir** [comment]
@ToXinE You are probably using a old version of requests.
You should us this command : run pip install requests --upgrade

**Comment by ToXinE** [comment]
this solved the problem. Thank you
