### ISSUE TITLE
error executing script with encoding

### ISSUE THREAD

**Issue by ToXinE** [danilovazb/GitMiner#4]
when running script 
`python git_miner.py -q 'filename:wp-config extension:php FTP_HOST in:file' -m wordpress -o result.txt`

```
| [USER]: @cesarbgvieira
| [LINK]: http://github.com/cesarbgvieira/ProjectosAngola/raw/baaa4af8cdf7e075b39c494d88d93822b04ccd8c/citic/wp-config.php
| [LAST INDEXED]: Oct 10, 2015
| [CONTAIN]: "root" IN LINE: 22
| [PARAM FOUND]:
| -------------> FTP_USER
| -------------> César Vieira
Traceback (most recent call last):
  File "git_miner.py", line 223, in <module>
    GitMiner().start()
  File "git_miner.py", line 220, in start
    self.parseSearch(HTML.content)
  File "git_miner.py", line 194, in parseSearch
    self.nextPage(prox_page)
  File "git_miner.py", line 73, in nextPage
    self.parseSearch(HTML.content)
  File "git_miner.py", line 194, in parseSearch
    self.nextPage(prox_page)
  File "git_miner.py", line 73, in nextPage
    self.parseSearch(HTML.content)
  File "git_miner.py", line 194, in parseSearch
    self.nextPage(prox_page)
  File "git_miner.py", line 73, in nextPage
    self.parseSearch(HTML.content)
  File "git_miner.py", line 194, in parseSearch
    self.nextPage(prox_page)
  File "git_miner.py", line 73, in nextPage
    self.parseSearch(HTML.content)
  File "git_miner.py", line 178, in parseSearch
    self.parseCode(code_boladao)
  File "git_miner.py", line 157, in parseCode
    self.saveOutput("| -------------> %s\n" % result_code[i])
  File "git_miner.py", line 66, in saveOutput
    arquivo.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 18: ordinal not in range(128)
```

in page 5/15 (Mars the 3rd 2016)

**Comment by danilovazb** [comment]
Solved, could test?
It was included two lines in the code.

Tks @tedmx

**Comment by tedmx** [comment]
@danilovazb Thanks for mention! I really want to leave a warning here: @ToXinE probably have a different (but related) issue.

If I got it right, @ToXinE uses standard cmd.exe but no UTF-8 encoding. @ToXinE uses ASCII encdoing. It breaks the Python script.

As a solution, I recommend to @ToXinE  to switch to Unicode encoding in cmd.exe as pointed here: http://stackoverflow.com/a/388500/402534

Please let me know if that helps.

**Comment by ToXinE** [comment]
I used [mobaxterm](http://mobaxterm.mobatek.net/) on my work computer which run under windows.
Git pull and now, it's working (in Putty) :)
